Repository Ree6-Applications/Ree6, pull requests merged in 2022-09, with the labels that each got.

#88 Statistic Channels
  pom.xml
  src/main/java/de/presti/ree6/bot/BotWorker.java
  src/main/java/de/presti/ree6/commands/impl/info/Stats.java
  src/main/java/de/presti/ree6/commands/impl/mod/Setup.java
  src/main/java/de/presti/ree6/events/OtherEvents.java
  src/main/java/de/presti/ree6/main/Main.java
  src/main/java/de/presti/ree6/sql/SQLConnector.java
  src/main/java/de/presti/ree6/sql/SQLWorker.java
  src/main/java/de/presti/ree6/sql/base/entities/StoredResultSet.java
  src/main/java/de/presti/ree6/sql/base/utils/SQLUtil.java
  src/main/java/de/presti/ree6/sql/entities/stats/ChannelStats.java
  src/main/java/de/presti/ree6/sql/entities/stats/CommandStats.java
  src/main/java/de/presti/ree6/sql/entities/stats/GuildCommandStats.java
  src/main/java/de/presti/ree6/sql/mapper/EntityMapper.java
  src/main/java/de/presti/ree6/utils/apis/Notifier.java
  src/main/java/de/presti/ree6/utils/apis/YouTubeAPIHandler.java
Labels: feature

#103 Fix/level update fix
  src/main/java/de/presti/ree6/events/OtherEvents.java
Labels: bug

#104 Menu Improvment.
  src/main/java/de/presti/ree6/commands/Category.java
  src/main/java/de/presti/ree6/commands/CommandManager.java
  src/main/java/de/presti/ree6/commands/impl/community/Birthday.java
  src/main/java/de/presti/ree6/commands/impl/hidden/Addon.java
  src/main/java/de/presti/ree6/commands/impl/info/Credits.java
  src/main/java/de/presti/ree6/commands/impl/info/Help.java
  src/main/java/de/presti/ree6/commands/impl/info/Invite.java
  src/main/java/de/presti/ree6/commands/impl/info/Support.java
  src/main/java/de/presti/ree6/commands/impl/level/Leaderboards.java
  src/main/java/de/presti/ree6/commands/impl/mod/Webinterface.java
  src/main/java/de/presti/ree6/main/Main.java
Labels: enhancement, p2

#110 Embed Sender
  src/main/java/de/presti/ree6/commands/CommandEvent.java
  src/main/java/de/presti/ree6/commands/impl/mod/EmbedSender.java
Labels: feature, p3

#112 Game-Core
  src/main/java/de/presti/ree6/bot/BotWorker.java
  src/main/java/de/presti/ree6/commands/impl/fun/Game.java
  src/main/java/de/presti/ree6/events/GameEvents.java
  src/main/java/de/presti/ree6/game/core/GameManager.java
  src/main/java/de/presti/ree6/game/core/GameSession.java
  src/main/java/de/presti/ree6/game/core/base/GameInfo.java
  src/main/java/de/presti/ree6/game/core/base/GamePlayer.java
  src/main/java/de/presti/ree6/game/core/base/IGame.java
  src/main/java/de/presti/ree6/main/Main.java
Labels: documentation, feature, p1

#111 Added Monkey Command to send a monke gif.
  src/main/java/de/presti/ree6/commands/impl/fun/Monkey.java
Labels: invalid, feature, p3

#120 Monitoring System
  src/main/java/de/presti/ree6/main/Main.java
  src/main/java/de/presti/ree6/sql/SQLWorker.java
  src/main/java/de/presti/ree6/sql/entities/stats/Statistics.java
Labels: enhancement, feature, p2

#116 Import command to import Mee6 Level stats.
  src/main/java/de/presti/ree6/commands/impl/mod/Import.java
Labels: feature, p3

#113 BlackJack - Game
  src/main/java/de/presti/ree6/game/impl/blackjack/Blackjack.java
  src/main/java/de/presti/ree6/game/impl/blackjack/entities/BlackJackCard.java
  src/main/java/de/presti/ree6/game/impl/blackjack/entities/BlackJackPlayer.java
  src/main/java/de/presti/ree6/game/impl/blackjack/util/BlackJackCardUtility.java
Labels: documentation, feature, p2
