Repository Ree6-Applications/Ree6, pull requests merged in 2022-10, with the labels that each got.

#129 Suggestions.
  src/main/java/de/presti/ree6/commands/impl/mod/Suggestion.java
  src/main/java/de/presti/ree6/events/OtherEvents.java
  src/main/java/de/presti/ree6/sql/entities/Suggestions.java
Labels: feature, p3

#109 Image welcome message.
  migrations/Data_Restructure_04_10_2022_14_26_55.migration
  src/main/java/de/presti/ree6/commands/impl/mod/Setup.java
  src/main/java/de/presti/ree6/events/OtherEvents.java
  src/main/java/de/presti/ree6/utils/data/ImageCreationUtility.java
Labels: enhancement, feature, p2

#133 !Gradle!
  .gitignore
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  pom.xml
  settings.gradle.kts
Labels: enhancement, p1

#153 Ticket System.
  src/main/java/de/presti/ree6/commands/impl/mod/Setup.java
  src/main/java/de/presti/ree6/events/MenuEvents.java
  src/main/java/de/presti/ree6/events/OtherEvents.java
  src/main/java/de/presti/ree6/main/Main.java
  src/main/java/de/presti/ree6/sql/entities/Tickets.java
  src/main/resources/sql/schema.sql
Labels: feature, p1
